function MyMex(filename)
addpath(genpath(pwd));
if(nargin == 0)
	filename = 'TestStieBrockett';
end
mex('-R2018a', '-IC:\Users\lenovo\Documents\MATLAB\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\hooks\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\info\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\logs\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\logs\refs\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\logs\refs\heads\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\logs\refs\remotes\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\logs\refs\remotes\origin\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\objects\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\objects\info\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\objects\pack\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\refs\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\refs\heads\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\refs\remotes\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\refs\remotes\origin\', ...
'-IC:\Users\lenovo\Documents\MATLAB\.git\refs\tags\', ...
'-IC:\Users\lenovo\Documents\MATLAB\BinaryFiles\', ...
'-IC:\Users\lenovo\Documents\MATLAB\LSTRSsoft\', ...
'-IC:\Users\lenovo\Documents\MATLAB\LSTRSsoft\Drivers\', ...
'-IC:\Users\lenovo\Documents\MATLAB\LSTRSsoft\ExampleMfuns\', ...
'-IC:\Users\lenovo\Documents\MATLAB\LSTRSsoft\Results\', ...
'-IC:\Users\lenovo\Documents\MATLAB\LSTRSsoft\Src\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\BinaryFiles\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Julia\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Matlab\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Matlab\ForCpp\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Matlab\ForMatlab\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\SparseBLAS\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\fftw\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\wavelet\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\cwrapper\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\cwrapper\blas\', ...
'-IC:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\cwrapper\lapack\', ...
'-IC:\Users\lenovo\Documents\MATLAB\datasets\', ...
'-IC:\Users\lenovo\Documents\MATLAB\figures\', ...
'-IC:\Users\lenovo\Documents\MATLAB\figures\rebuttal\', ...
'-IC:\Users\lenovo\Documents\MATLAB\result\', ...
'-IC:\Users\lenovo\Documents\MATLAB\result\synthetic_result\', ...
'-IC:\Users\lenovo\Documents\MATLAB\result\synthetic_result\gamma0.01\', ...
'-IC:\Users\lenovo\Documents\MATLAB\result\synthetic_result\gamma0.1\', ...
'-IC:\Users\lenovo\Documents\MATLAB\test\', ...
['.\test\' filename '.cpp'], ...
'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\CFixedRankQ2F.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\CStiefel.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\CSymFixedRankQ.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\Element.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\Euclidean.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\FixedRankE.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\FixedRankQ2F.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\Grassmann.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\Manifold.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\MultiManifolds.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\SPDManifold.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\SmartSpace.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\Sphere.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\SphereTx.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\Stiefel.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Manifolds\SymFixedRankQ.cpp', ...
'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\BlasLapackCppWrapper.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\ForDebug.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\MinPNormConHull.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\SparseMatrix.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\Spline.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\Timer.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\randgen.cpp', ...
'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\SparseBLAS\nist_spblas.cpp', ...
'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Others\wavelet\wavelet.cpp', ...
'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\CFRankQ2FBlindDecon2D.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\CSFRQPhaseRetrieval.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\CStieBrockett.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\EucQuadratic.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\FRankESparseApprox.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\FRankEWeightApprox.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\FRankQ2FMatCompletion.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\GrassRQ.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\Problem.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\ProdStieSumBrockett.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\SFRQLyapunov.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\SPDKarcherMean.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\SphereConvexHull.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\SphereSparsestVector.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\SphereTxRQ.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\StieBrockett.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\StieSPCA.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\juliaProblem.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Problems\mexProblem.cpp', ...
'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\AManPG.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\LRBFGS.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\LRBFGSSub.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\LRTRSR1.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\ManPG.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RBFGS.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RBFGSSub.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RBroydenFamily.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RCG.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RGS.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RNewton.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RSD.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RTRNewton.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RTRSD.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RTRSR1.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\RWRBFGS.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\Solvers.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\SolversNSM.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\SolversNSMPGLS.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\SolversNSMSub.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\SolversNSMSubLS.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\SolversSM.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\SolversSMLS.cpp', 'C:\Users\lenovo\Documents\MATLAB\ROPTLIB_2020-08-11\Solvers\SolversSMTR.cpp', ...
['-D' upper(filename)], 'D:\UserApps\MATLABr2021a\extern\lib\win64\microsoft\libmwblas.lib', 'D:\UserApps\MATLABr2021a\extern\lib\win64\microsoft\libmwlapack.lib', '-output', ['.\BinaryFiles\' filename ]);
end